######################################################################
#       Global SERVICE exposed to outside via K8S Master Node        #
#     kubectl port-forward service/quiz-service 7088:8888            #
######################################################################

apiVersion:       v1
kind:             Service

metadata:
  name:           quiz-service

spec:
  selector:
    app:          quiz-pod

  type:           NodePort

  ports:
    - port:       8888
      targetPort: 8888